### ISSUE TITLE
Here works nothing

### ISSUE THREAD

**Issue by noragen** [Instagram/MonkeyType#157] opened 2019-12-11 16:05 UTC
```bash
$ cat myscript.py
from some.module import add

add(1, 2)

$ cat some/module.py
def add(a, b):
    return a + b

$ monkeytype run myscript.py

$ monkeytype stub some.module
No traces found for module some.module
```

Your examples...

**Comment by carljm** [comment] 2019-12-11 19:04
I just created a new virtual environment, ran `pip install monkeytype` to install the latest version, recreated the above files, and ran `monkeytype run myscript.py` followed by `monkeytype stub some.module`, and the output I get is `def add(a: int, b: int) -> int: ...`. So I'm afraid I can't reproduce this problem without more details about your environment.

What version of Python? Inside or outside a virtualenv? Do you see a `monkeytype.sqlite3` file in your cwd after running `monkeytype run myscript.py`? If you run `sqlite3 monkeytype.sqlite3` and then `select * from monkeytype_call_traces` at the SQLite prompt, are any rows returned?

Closing for now since this is non-actionable for MonkeyType, will re-open if you can provide more information that allows a repro.

Thanks for the report, and sorry for the difficulty!

**Closed by carljm** 2019-12-11 19:04 UTC

**Comment by noragen** [comment] 2019-12-12 09:43
Hi, 
thanks for the hints! 😊
My setup is following:

```shell
(base) C:\projects>conda info

     active environment : base
    active env location : C:\Anaconda3
            shell level : 1
       user config file : C:\Users\tfz\.condarc
 populated config files : C:\Users\tfz\.condarc
          conda version : 4.7.12
    conda-build version : 3.18.11
         python version : 3.7.3.final.0
       virtual packages :
       base environment : C:\Anaconda3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
                          https://conda.anaconda.org/bioconda/win-64
                          https://conda.anaconda.org/bioconda/noarch
          package cache : C:\Anaconda3\pkgs
                          C:\Users\tfz\.conda\pkgs
                          C:\Users\tfz\AppData\Local\conda\conda\pkgs
       envs directories : C:\Anaconda3\envs
                          C:\Users\tfz\.conda\envs
                          C:\Users\tfz\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.7.12 requests/2.22.0 CPython/3.7.3 Windows/10 Windows/10.0.18362
          administrator : False
             netrc file : None
           offline mode : False

(base) C:\projects>conda list monkeytype
# packages in environment at C:\Anaconda3:
#
# Name                    Version                   Build  Channel
monkeytype                19.11.2            pyh516909a_0    conda-forge
```

The monkeytype.sqlite3 is there, but seems to be empty. Pls see the attachment.
[monkeytype.zip](https://github.com/Instagram/MonkeyType/files/3954963/monkeytype.zip)

I'm very thankful, that there are so guys like you who responds so fast!
Thank you very much in advance! 😉

If you need more information or when you could give some debug hints, I really would like to help.

Best regards!

**Comment by noragen** [comment] 2019-12-16 16:06
> Requirements
> 
> MonkeyType requires Python 3.6+ and the retype library (for applying type stubs to code files). It generates only Python 3 type annotations (no type comments).

Seems like the python version is the reason, because I got to run that with the newer 3.8:

```shell
(py38) C:\projects\deploy>conda info

     active environment : py38
    active env location : C:\Anaconda3\envs\py38
            shell level : 2
       user config file : C:\Users\tfz\.condarc
 populated config files : C:\Users\tfz\.condarc
          conda version : 4.8.0
    conda-build version : 3.18.11
         python version : 3.7.3.final.0
       virtual packages :
       base environment : C:\Anaconda3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
                          https://conda.anaconda.org/bioconda/win-64
                          https://conda.anaconda.org/bioconda/noarch
          package cache : C:\Anaconda3\pkgs
                          C:\Users\tfz\.conda\pkgs
                          C:\Users\tfz\AppData\Local\conda\conda\pkgs
       envs directories : C:\Anaconda3\envs
                          C:\Users\tfz\.conda\envs
                          C:\Users\tfz\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.8.0 requests/2.22.0 CPython/3.7.3 Windows/10 Windows/10.0.18362
          administrator : False
             netrc file : None
           offline mode : False
```
