### ISSUE TITLE
Running monkeytype directly from venv

### ISSUE THREAD

**Issue by csernazs** [Instagram/MonkeyType#160] opened 2019-12-20 12:51 UTC
When I create a venv and install monkeytype like this:

```
python3 -m venv /tmp/venv
/tmp/venv/bin/pip install MonkeyType
```

And then I run monkeytype like this:
```
/tmp/venv/bin/monkeytype run foo.py
/tmp/venv/bin/monkeytype apply example
```

Then it fails with this error:
```
Traceback (most recent call last):
  File "/tmp/venv/bin/monkeytype", line 11, in <module>
    sys.exit(entry_point_main())
  File "/tmp/venv/lib/python3.6/site-packages/monkeytype/cli.py", line 382, in entry_point_main
    sys.exit(main(sys.argv[1:], sys.stdout, sys.stderr))
  File "/tmp/venv/lib/python3.6/site-packages/monkeytype/cli.py", line 367, in main
    handler(args, stdout, stderr)
  File "/tmp/venv/lib/python3.6/site-packages/monkeytype/cli.py", line 165, in apply_stub_handler
    proc = subprocess.run(retype_args, check=True, stderr=subprocess.STDOUT, stdout=subprocess.PIPE)
  File "/usr/lib/python3.6/subprocess.py", line 423, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'retype': 'retype'
```

As `retype` is not in my path.

It would be very great to run the `retype` execuable from the venv also, as it is installed to the bin directory in the venv.

I can workaround this issue by activating the venv before but it is a bit inconvenient for me.

**Comment by carljm** [comment] 2020-02-22 05:26
I guess we could look for the `retype` binary next to the running `sys.executable` and run that via full path if found. Would take a PR for that! Thanks for the report.

**Comment by Jongy** [comment] 2020-07-21 22:34
Can't reproduce with MonkeyType `20.5.0`, this erroneous code doesn't exist anymore? Anyway, I can `run ..` then `apply` successfully while in a virtual env.

**Comment by carljm** [comment] 2020-07-22 00:33
This was fixed with the switch from `retype` to LibCST for applying type annotations. Thanks for the nudge to close it!

**Closed by carljm** 2020-07-22 00:33 UTC
Labels: bug
