### ISSUE TITLE
MonkeyType fails to distinguish typing.Generator and numpy.random.Generator

### ISSUE THREAD

**Issue by gramster** [Instagram/MonkeyType#281] opened 2022-12-16 23:29 UTC
It seems MonkeyType gets confused between typing.Generator and other classes named Generator (even if they are qualified).

```
  File "/Users/grwheele/.virtualenvs/docs2stubs/lib/python3.10/site-packages/monkeytype/stubs.py", line 817, in build_module_stubs_from_traces
    defn = get_updated_definition(func, traces, max_typed_dict_size, rewriter, existing_annotation_strategy)
  File "/Users/grwheele/.virtualenvs/docs2stubs/lib/python3.10/site-packages/monkeytype/stubs.py", line 763, in get_updated_definition
    return_type = rewriter.rewrite(return_type)
  File "/Users/grwheele/.virtualenvs/docs2stubs/lib/python3.10/site-packages/monkeytype/typing.py", line 424, in rewrite
    typ = rw.rewrite(typ)
  File "/Users/grwheele/.virtualenvs/docs2stubs/lib/python3.10/site-packages/monkeytype/typing.py", line 293, in rewrite
    return rewriter(typ)
  File "/Users/grwheele/.virtualenvs/docs2stubs/lib/python3.10/site-packages/monkeytype/typing.py", line 437, in rewrite_Generator
    args = typ.__args__
AttributeError: type object 'numpy.random._generator.Generator' has no attribute '__args__'
```

**Comment by carljm** [comment] 2022-12-22 00:52
Yes, thanks for the report. This is a known issue (#54) that we just haven't been able to prioritize fixing. The design of a fix is outlined there, and pull requests certainly welcome! (There could also be smaller short-term fixes where in various rewriter methods we just check with `isinstance` to make sure we have the right type and bail out if not.)

In the meantime the only workaround I know of would be to not use (in this particular scenario) the `RewriteGenerator` rewriter, by defining your own config that omits it from the type rewriters list. (Could also add your own version of `RewriteGenerator` that checks with `isinstance`.)

Closing as duplicate of #54.

**Closed by carljm** 2022-12-22 00:52 UTC
