### ISSUE TITLE
factory paradigm and multiple inheritance errors

### ISSUE THREAD

**Issue by johnarnold** [Instagram/MonkeyType#63] opened 2018-01-29 20:04 UTC
Hi,

I'm getting errors like:
Module 'module.factory' has no attribute 'Class1_Class2'  where the factory module is binding a custom class inherited from Class1 and Class2.

All of the traces are for the 'Class1_Class2' custom class, rather than the base classes it inherits from, so the traces don't match up.

Any ideas or suggestions on how to make monkeytype work with derived classes like this?

Thanks,
John

**Comment by carljm** [comment] 2018-01-29 23:29
Can you give a minimal code sample that reproduces the issue? I'm not sure what you mean by "the factory module is binding a custom class inherited from Class1 and Class2." If you're doing some kind of dynamic class generation, that should still work as long as the class is bound to the name `Class1_Class2` in the module namespace.

Closing since if this is the issue I think it is, it's really a variant of #36. Not really sure how we can or will handle that in MonkeyType. If you can add a code sample demonstrating your use case there, that would help.

**Closed by carljm** 2018-01-29 23:29 UTC
