### ISSUE TITLE
Handling alternative class constructors

### ISSUE THREAD

**Issue by jspaezp** [Instagram/MonkeyType#225] opened 2021-02-09 17:31 UTC
Hello,

I was wondering what can be done either to correctly annotate alternative constructors for a class or what can be done to prevent monkeytype failing during the annotation process.

(just for illustration purposes...) If I have for instance a class that has the standard `__init__` constructor and an alternative `from_string` method.

```
class Foo:
    def __init__(self):
        self.var = "Foo"

    @classmethod
    def from_string(cls, my_string):
        self = cls(my_string)
        return self 
```

It gets annotated as such when using `monkeytype run` > `monkeytype apply`

```
class Foo:
    def __init__(self) -> None:
        self.var = "Foo"

    @classmethod
    def from_string(cls, my_string: str) -> Foo:
        self = cls(my_string)
        return self 
```

Which looks logical to me but fails at runtime because the Foo class has not been defined when the type hint is called with with a `NameError`

```
NameError: name 'Foo' is not defined
```

Should this be considered a bug in monkeytype or a limitation of the type hinting in python? (or both)

Appreciating your help,
Best!

**Comment by carljm** [comment] 2021-02-09 17:36
Hi! Thanks for the report. I think you've identified one specific case of the more general pattern of forward references needing quoting, which is an awkwardness of Python typing generally that also affects MonkeyType. So far, our best idea for resolving that is described in #203. If it's OK with you, I'll close this issue as duplicate of that one.

**Closed by carljm** 2021-02-09 17:36 UTC

**Comment by jspaezp** [comment] 2021-02-09 17:40
Thank you so much for the (extremely quick response), indeed `from __future__ import annotations` solves the issue

Kindest wishes
