### ISSUE TITLE
Getting '_SpecialForm' object has no attribute '__name__'

### ISSUE THREAD

**Issue by CaselIT** [Instagram/MonkeyType#243] opened 2021-06-26 20:14 UTC
I'm getting this error running monkeytype 21.5 on python 3.8:

```
monkeytype run -m pytest tests
Failed collecting trace
Traceback (most recent call last):
  File "path\to\env\lib\site-packages\monkeytype\tracing.py", line 259, in __call__
    self.handle_call(frame)
  File "path\to\env\lib\site-packages\monkeytype\tracing.py", line 225, in handle_call
    arg_types[name] = get_type(frame.f_locals[name],
  File "path\to\env\lib\site-packages\monkeytype\typing.py", line 190, in get_type
    return get_dict_type(obj, max_typed_dict_size)
  File "path\to\env\lib\site-packages\monkeytype\typing.py", line 170, in get_dict_type
    val_type = shrink_types((get_type(v, max_typed_dict_size) for v in dct.values()), max_typed_dict_size)
  File "path\to\env\lib\site-packages\monkeytype\typing.py", line 133, in shrink_types
    annotation = shrink_types((getattr(typ, '__args__')[0] for typ in types), max_typed_dict_size)
  File "path\to\env\lib\site-packages\monkeytype\typing.py", line 132, in shrink_types
    if all(is_list(typ) for typ in types):
  File "path\to\env\lib\site-packages\monkeytype\typing.py", line 132, in <genexpr>
    if all(is_list(typ) for typ in types):
  File "path\to\env\lib\site-packages\monkeytype\typing.py", line 54, in is_list
    return is_generic(typ) and name_of_generic(typ) == 'List'
  File "path\to\env\lib\site-packages\monkeytype\compat.py", line 43, in name_of_generic
    return typ._name or typ.__origin__.__name__
AttributeError: '_SpecialForm' object has no attribute '__name__'
```
Using 20.5 works correctly instead.
This happens while running monkeytype on alembic.

To reproduce (commit e31971cfb46efd0ef41525473a1d9bcb81e90f43 is the current head of alembic):
```sh
git clone https://github.com/sqlalchemy/alembic.git
cd alembic
git checkout e31971cfb46efd0ef41525473a1d9bcb81e90f43
pip install -e .
pip install python-dateutil
monkeytype run -m pytest tests
```

**Comment by carljm** [comment] 2021-06-30 00:05
Thanks for the report!

I'm not able to reproduce this. I'm using Python 3.8.7, and I followed your repro instructions exactly, plus a `pip install pytest` that I needed in order to have pytest installed in the virtualenv. I've tried with both MonkeyType 21.5 and the latest main branch, and in both cases `monkeytype run -m pytest tests` runs successfully to completion (1357 tests passed, 378 skipped).

Are you using an older Python 3.8? If so, can you try a more recent one?

**Comment by CaselIT** [comment] 2021-06-30 19:44
I think I got a reproducer. I had sqlalchemy (required by alembic) installed in editable mode in my env. Installing it normally from pypi seems to not present the issue

I can reproduce from en empty docker image by doing:
```py
git clone https://github.com/sqlalchemy/sqlalchemy.git  --depth 10
pip install -e sqlalchemy
git clone https://github.com/sqlalchemy/alembic.git
cd alembic
git checkout e31971cfb46efd0ef41525473a1d9bcb81e90f43
pip install -e .
pip install python-dateutil pytest monkeytype
monkeytype run -m pytest tests
```

error is:
```
root@67b5077b0c67:/alembic# monkeytype run -m pytest tests
Failed collecting trace
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/monkeytype/tracing.py", line 259, in __call__
    self.handle_call(frame)
  File "/usr/local/lib/python3.9/site-packages/monkeytype/tracing.py", line 225, in handle_call
    arg_types[name] = get_type(frame.f_locals[name],
  File "/usr/local/lib/python3.9/site-packages/monkeytype/typing.py", line 190, in get_type
    return get_dict_type(obj, max_typed_dict_size)
  File "/usr/local/lib/python3.9/site-packages/monkeytype/typing.py", line 170, in get_dict_type
    val_type = shrink_types((get_type(v, max_typed_dict_size) for v in dct.values()), max_typed_dict_size)
  File "/usr/local/lib/python3.9/site-packages/monkeytype/typing.py", line 133, in shrink_types
    annotation = shrink_types((getattr(typ, '__args__')[0] for typ in types), max_typed_dict_size)
  File "/usr/local/lib/python3.9/site-packages/monkeytype/typing.py", line 132, in shrink_types
    if all(is_list(typ) for typ in types):
  File "/usr/local/lib/python3.9/site-packages/monkeytype/typing.py", line 132, in <genexpr>
    if all(is_list(typ) for typ in types):
  File "/usr/local/lib/python3.9/site-packages/monkeytype/typing.py", line 54, in is_list
    return is_generic(typ) and name_of_generic(typ) == 'List'
  File "/usr/local/lib/python3.9/site-packages/monkeytype/compat.py", line 43, in name_of_generic
    return typ._name or typ.__origin__.__name__
AttributeError: '_SpecialForm' object has no attribute '__name__'
========================================================== test session starts ===========================================================
platform linux -- Python 3.9.6, pytest-6.2.4, py-1.10.0, pluggy-0.13.1 -- /usr/local/bin/python
cachedir: .pytest_cache
rootdir: /alembic, configfile: setup.cfg
```

packages installed are
```
root@67b5077b0c67:/alembic# pip list
Package           Version     Location
----------------- ----------- ---------------
alembic           1.7.0.dev0  /alembic
attrs             21.2.0
greenlet          1.1.0
iniconfig         1.1.1
libcst            0.3.19
Mako              1.1.4
MarkupSafe        2.0.1
MonkeyType        21.5.0
mypy-extensions   0.4.3
packaging         20.9
pip               21.1.3
pluggy            0.13.1
py                1.10.0
pyparsing         2.4.7
pytest            6.2.4
python-dateutil   2.8.1
PyYAML            5.4.1
setuptools        57.0.0
six               1.16.0
SQLAlchemy        1.4.21.dev0 /sqlalchemy/lib
toml              0.10.2
typing-extensions 3.10.0.0
typing-inspect    0.7.1
wheel             0.36.2
```

**Comment by carljm** [comment] 2021-06-30 23:38
Unfortunately I'm still not able to repro, I still get a successful passing test run running `monkeytype run -m pytest tests` with these dependencies:

```
➜ pip list
Package           Version     Location
----------------- ----------- -------------------------------------
alembic           1.7.0.dev0  /Users/carljm/projects/alembic
attrs             21.2.0
greenlet          1.1.0
iniconfig         1.1.1
libcst            0.3.19
Mako              1.1.4
MarkupSafe        2.0.1
MonkeyType        21.5.0
mypy-extensions   0.4.3
packaging         20.9
pip               21.1.3
pluggy            0.13.1
py                1.10.0
pyparsing         2.4.7
pytest            6.2.4
python-dateutil   2.8.1
PyYAML            5.4.1
setuptools        57.0.0
six               1.16.0
SQLAlchemy        1.4.21.dev0 /Users/carljm/projects/sqlalchemy/lib
toml              0.10.2
typing-extensions 3.10.0.0
typing-inspect    0.7.1
wheel             0.36.2
```

**Comment by CaselIT** [comment] 2021-07-01 05:42
After the error log the tests keep executing, but I've not tried to look if the traces were saved (i stopped before the end of the tests)

Does the error get printed on startup in your case?

I'll try sharing a dockerfile that hopefully can reproduce the error since it seem to be environment dependent

**Comment by CaselIT** [comment] 2021-07-01 07:55
This docker file will reproduce the issue when starting:
```dockerfile
FROM python:3.9.6-slim-buster

RUN apt update && apt install -y git

RUN \
    git clone https://github.com/sqlalchemy/sqlalchemy.git  --depth 10 && \
    pip install -e sqlalchemy && \
    git clone https://github.com/sqlalchemy/alembic.git && \
    cd alembic && \
    git checkout e31971cfb46efd0ef41525473a1d9bcb81e90f43 && \
    pip install -e . && \
    pip install python-dateutil pytest monkeytype

WORKDIR alembic
CMD [ "monkeytype", "run", "-m", "pytest", "tests" ]
```

After the error is logged the tests seem to keep running and it does seem that monkeytype processes the output.

Example log of running just the `tests/test_config.py` file:
```
root@86e21837f701:/alembic# monkeytype run -m pytest tests/test_config.py
Failed collecting trace
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/monkeytype/tracing.py", line 259, in __call__
    self.handle_call(frame)
  File "/usr/local/lib/python3.9/site-packages/monkeytype/tracing.py", line 225, in handle_call
    arg_types[name] = get_type(frame.f_locals[name],
  File "/usr/local/lib/python3.9/site-packages/monkeytype/typing.py", line 190, in get_type
    return get_dict_type(obj, max_typed_dict_size)
  File "/usr/local/lib/python3.9/site-packages/monkeytype/typing.py", line 170, in get_dict_type
    val_type = shrink_types((get_type(v, max_typed_dict_size) for v in dct.values()), max_typed_dict_size)
  File "/usr/local/lib/python3.9/site-packages/monkeytype/typing.py", line 133, in shrink_types
    annotation = shrink_types((getattr(typ, '__args__')[0] for typ in types), max_typed_dict_size)
  File "/usr/local/lib/python3.9/site-packages/monkeytype/typing.py", line 132, in shrink_types
    if all(is_list(typ) for typ in types):
  File "/usr/local/lib/python3.9/site-packages/monkeytype/typing.py", line 132, in <genexpr>
    if all(is_list(typ) for typ in types):
  File "/usr/local/lib/python3.9/site-packages/monkeytype/typing.py", line 54, in is_list
    return is_generic(typ) and name_of_generic(typ) == 'List'
  File "/usr/local/lib/python3.9/site-packages/monkeytype/compat.py", line 43, in name_of_generic
    return typ._name or typ.__origin__.__name__
AttributeError: '_SpecialForm' object has no attribute '__name__'
=================================================================================================================== test session starts ====================================================================================================================
platform linux -- Python 3.9.6, pytest-6.2.4, py-1.10.0, pluggy-0.13.1 -- /usr/local/bin/python
cachedir: .pytest_cache
rootdir: /alembic, configfile: setup.cfg
collected 26 items

tests/test_config.py::ConfigTest::test_attributes_attr PASSED                                                                                                                                                                                        [  3%]
tests/test_config.py::ConfigTest::test_attributes_construtor PASSED                                                                                                                                                                                  [  7%]
tests/test_config.py::ConfigTest::test_config_no_file_main_option PASSED                                                                                                                                                                             [ 11%]
tests/test_config.py::ConfigTest::test_config_no_file_section_option PASSED                                                                                                                                                                          [ 15%]
tests/test_config.py::ConfigTest::test_config_set_main_option_percent PASSED                                                                                                                                                                         [ 19%]
tests/test_config.py::ConfigTest::test_config_set_section_option_interpolation PASSED                                                                                                                                                                [ 23%]
tests/test_config.py::ConfigTest::test_config_set_section_option_percent PASSED                                                                                                                                                                      [ 26%]
tests/test_config.py::ConfigTest::test_no_script_error PASSED                                                                                                                                                                                        [ 30%]
tests/test_config.py::ConfigTest::test_standalone_op PASSED                                                                                                                                                                                          [ 34%]
tests/test_config.py::ConfigTest::test_version_locations[Linux pathsep 1] PASSED                                                                                                                                                                     [ 38%]
tests/test_config.py::ConfigTest::test_version_locations[Linux pathsep 2] PASSED                                                                                                                                                                     [ 42%]
tests/test_config.py::ConfigTest::test_version_locations[Windows pathsep 1] PASSED                                                                                                                                                                   [ 46%]
tests/test_config.py::ConfigTest::test_version_locations[Windows pathsep 2] PASSED                                                                                                                                                                   [ 50%]
tests/test_config.py::ConfigTest::test_version_locations[invalid pathsep 2] PASSED                                                                                                                                                                   [ 53%]
tests/test_config.py::ConfigTest::test_version_locations[legacy raw string 1] PASSED                                                                                                                                                                 [ 57%]
tests/test_config.py::ConfigTest::test_version_locations[legacy raw string 2] PASSED                                                                                                                                                                 [ 61%]
tests/test_config.py::ConfigTest::test_version_locations[legacy raw string 3] PASSED                                                                                                                                                                 [ 65%]
tests/test_config.py::ConfigTest::test_version_locations[legacy raw string 4] PASSED                                                                                                                                                                 [ 69%]
tests/test_config.py::ConfigTest::test_version_locations[os pathsep] PASSED                                                                                                                                                                          [ 73%]
tests/test_config.py::FileConfigTest::test_config_args PASSED                                                                                                                                                                                        [ 76%]
tests/test_config.py::StdoutOutputEncodingTest::test_ascii_unicode PASSED                                                                                                                                                                            [ 80%]
tests/test_config.py::StdoutOutputEncodingTest::test_only_formats_output_with_args PASSED                                                                                                                                                            [ 84%]
tests/test_config.py::StdoutOutputEncodingTest::test_plain PASSED                                                                                                                                                                                    [ 88%]
tests/test_config.py::StdoutOutputEncodingTest::test_utf8_unicode PASSED                                                                                                                                                                             [ 92%]
tests/test_config.py::TemplateOutputEncodingTest::test_default PASSED                                                                                                                                                                                [ 96%]
tests/test_config.py::TemplateOutputEncodingTest::test_setting PASSED                                                                                                                                                                                [100%]Failed collecting trace
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/monkeytype/tracing.py", line 259, in __call__
    self.handle_call(frame)
  File "/usr/local/lib/python3.9/site-packages/monkeytype/tracing.py", line 225, in handle_call
    arg_types[name] = get_type(frame.f_locals[name],
  File "/usr/local/lib/python3.9/site-packages/monkeytype/typing.py", line 190, in get_type
    return get_dict_type(obj, max_typed_dict_size)
  File "/usr/local/lib/python3.9/site-packages/monkeytype/typing.py", line 170, in get_dict_type
    val_type = shrink_types((get_type(v, max_typed_dict_size) for v in dct.values()), max_typed_dict_size)
  File "/usr/local/lib/python3.9/site-packages/monkeytype/typing.py", line 133, in shrink_types
    annotation = shrink_types((getattr(typ, '__args__')[0] for typ in types), max_typed_dict_size)
  File "/usr/local/lib/python3.9/site-packages/monkeytype/typing.py", line 132, in shrink_types
    if all(is_list(typ) for typ in types):
  File "/usr/local/lib/python3.9/site-packages/monkeytype/typing.py", line 132, in <genexpr>
    if all(is_list(typ) for typ in types):
  File "/usr/local/lib/python3.9/site-packages/monkeytype/typing.py", line 54, in is_list
    return is_generic(typ) and name_of_generic(typ) == 'List'
  File "/usr/local/lib/python3.9/site-packages/monkeytype/compat.py", line 43, in name_of_generic
    return typ._name or typ.__origin__.__name__
AttributeError: '_SpecialForm' object has no attribute '__name__'


==================================================================================================================== 26 passed in 0.54s ====================================================================================================================
root@86e21837f701:/alembic# ls
CHANGES  LICENSE  MANIFEST.in  README.rst  README.unittests.rst  alembic  alembic.egg-info  docs  monkeytype.sqlite3  pyproject.toml  reap_dbs.py  setup.cfg  setup.py  tests  tox.ini
```

The `monkeytype.sqlite3` is generated, so it seems that the process was successful despite the error.

Not sure it it's just a log the printed exception then

**Comment by jiridanek** [comment] 2021-07-01 15:58
I've encountered the same issue. It appears only in some tests, so it probably depends on what the test code is doing. Is there something I can do to help you reproduce this?

```
40: Test command: /home/jdanek/.local/share/virtualenvs/qpid-dispatch-Wxq-GF1B/bin/python "/home/jdanek/repos/qpid/qpid-dispatch/cmake-build-release/tests/run.py" "monkeytype" "run" "-m" "unittest" "-v" "system_tests_dynamic_terminus"
40: Test timeout computed to be: 600
40: Failed collecting trace
40: Traceback (most recent call last):
40:   File "/home/jdanek/.local/share/virtualenvs/qpid-dispatch-Wxq-GF1B/lib/python3.9/site-packages/monkeytype/tracing.py", line 259, in __call__
40:     self.handle_call(frame)
40:   File "/home/jdanek/.local/share/virtualenvs/qpid-dispatch-Wxq-GF1B/lib/python3.9/site-packages/monkeytype/tracing.py", line 225, in handle_call
40:     arg_types[name] = get_type(frame.f_locals[name],
40:   File "/home/jdanek/.local/share/virtualenvs/qpid-dispatch-Wxq-GF1B/lib/python3.9/site-packages/monkeytype/typing.py", line 184, in get_type
40:     elem_type = shrink_types((get_type(e, max_typed_dict_size) for e in obj), max_typed_dict_size)
40:   File "/home/jdanek/.local/share/virtualenvs/qpid-dispatch-Wxq-GF1B/lib/python3.9/site-packages/monkeytype/typing.py", line 133, in shrink_types
40:     annotation = shrink_types((getattr(typ, '__args__')[0] for typ in types), max_typed_dict_size)
40:   File "/home/jdanek/.local/share/virtualenvs/qpid-dispatch-Wxq-GF1B/lib/python3.9/site-packages/monkeytype/typing.py", line 132, in shrink_types
40:     if all(is_list(typ) for typ in types):
40:   File "/home/jdanek/.local/share/virtualenvs/qpid-dispatch-Wxq-GF1B/lib/python3.9/site-packages/monkeytype/typing.py", line 132, in <genexpr>
40:     if all(is_list(typ) for typ in types):
40:   File "/home/jdanek/.local/share/virtualenvs/qpid-dispatch-Wxq-GF1B/lib/python3.9/site-packages/monkeytype/typing.py", line 54, in is_list
40:     return is_generic(typ) and name_of_generic(typ) == 'List'
40:   File "/home/jdanek/.local/share/virtualenvs/qpid-dispatch-Wxq-GF1B/lib/python3.9/site-packages/monkeytype/compat.py", line 43, in name_of_generic
40:     return typ._name or typ.__origin__.__name__
40: AttributeError: '_SpecialForm' object has no attribute '__name__'
40: test_01_dynamic_source_test (system_tests_dynamic_terminus.RouterTest) ... ok
40: test_02_dynamic_target_one_router_test (system_tests_dynamic_terminus.RouterTest) ... ok
40: test_03_dynamic_target_two_router_test (system_tests_dynamic_terminus.RouterTest) ... ok
40: 
40: ----------------------------------------------------------------------
40: Ran 3 tests in 4.876s
40: 
40: OK
40/75 Test #40: system_tests_dynamic_terminus .....................   Passed    7.48 sec
```

**Comment by carljm** [comment] 2021-07-01 23:09
Ok I was able to repro this, thanks for the report and the repro help! Should be fixed by 5517cdb760fdc82d0d2108ee65b5e5717f84d0e5

**Closed** 2021-07-01 23:09 UTC
Labels: need-info

**Comment by CaselIT** [comment] 2021-07-02 06:30
Thanks for the quick fix

**Comment by jiridanek** [comment] 2021-07-02 07:44
That fixed it for me too. Thanks!

**Comment by roshcagra** [comment] 2021-11-11 23:18
Hi! It looks like this was added after the most recent release - is there a plan to push a new version with this fix soon?

**Comment by eggplants** [comment] 2022-02-18 20:05
I faced this problem and fixed by using HEAD.
I can't wait for new release!

**Comment by carljm** [comment] 2022-02-18 23:49
New release is up: https://pypi.org/project/MonkeyType/22.2.0/

Sorry for the delay.
