### ISSUE TITLE
invalid syntax when applying type

### ISSUE THREAD

**Issue by bluebird75** [Instagram/MonkeyType#113] opened 2018-09-26 04:25 UTC
While running `monkeytype apply`, I received : 

```
d:\work\pyann\monkeytype\toto>monkeytype apply forward_ref
ERROR: Failed applying stub with retype:
error: d:\work\pyann\monkeytype\toto\forward_ref.py: invalid syntax (<unknown>, line 8)
```

I was actually trying to reproduce a bug-case for forward references with nested classes, which I encountered at work.

The exact files to reproduce this issue are  : 

**forward_ref.py:**
```
class AA:

    def use_aa( self, aa ):
        pass

    def use_bb( self, bb ):
        pass

    def use_cc( self, cc ):
        pass

    def use_dd( self, dd ):
        pass

    class CC:

        def use_aa( self, aa ):
            pass

        def use_bb( self, bb ):
            pass

        def use_cc( self, cc ):
            pass

        def use_dd( self, dd ):
            pass

        class DD:

            def use_aa( self, aa ):
                pass

            def use_bb( self, bb ):
                pass

            def use_cc( self, cc ):
                pass

            def use_dd( self, dd ):
                pass

class BB:
    pass
```

And use_fw_ref.py : 
```
from forward_ref import AA, BB

if __name__ == '__main__':
    aa = AA()
    bb = BB()
    cc = AA.CC()
    dd = AA.CC.DD()

    for inst in (aa, cc, dd):
        inst.use_aa( aa )
        inst.use_bb( bb )
        inst.use_cc( cc )
        inst.use_dd( dd )
```

Then using them : 

```
d:\work\pyann\monkeytype\toto>monkeytype run use_fw_ref.py
d:\work\pyann\monkeytype\toto>monkeytype list-modules
forward_ref
d:\work\pyann\monkeytype\toto>monkeytype apply forward_ref
ERROR: Failed applying stub with retype:
error: d:\work\pyann\monkeytype\toto\forward_ref.py: invalid syntax (<unknown>, line 8)
d:\work\pyann\monkeytype\toto>
```

There is no error generated if I generate the stub, so this is probably an issue with parsing, or even a forward reference which confuses internally monkeytype.

```
d:\work\pyann\monkeytype\toto>monkeytype stub forward_ref
class AA:
    def use_aa(self, aa: AA) -> None: ...
    def use_bb(self, bb: BB) -> None: ...
    def use_cc(self, cc: AA.CC) -> None: ...
    def use_dd(self, dd: AA.CC.DD) -> None: ...


class AA.CC:
    def use_aa(self, aa: AA) -> None: ...
    def use_bb(self, bb: BB) -> None: ...
    def use_cc(self, cc: AA.CC) -> None: ...
    def use_dd(self, dd: AA.CC.DD) -> None: ...


class AA.CC.DD:
    def use_aa(self, aa: AA) -> None: ...
    def use_bb(self, bb: BB) -> None: ...
    def use_cc(self, cc: AA.CC) -> None: ...
    def use_dd(self, dd: AA.CC.DD) -> None: ...
```

**Comment by bluebird75** [comment] 2018-09-26 04:28
I wanted to run monkeytype into a debugger to understand in depth where the issue is coming from, but I fail to execute it on command-line : 
```
d:\work\pyann\monkeytype>py -3.7 monkeytype\cli.py
['d:\\work\\pyann\\monkeytype\\monkeytype', 'C:\\Program Files (x86)\\Python37-32\\python37.zip', 'C:\\Program Files (x86)\\Python37-32\\DLLs', 'C:\\Program Files (x86)\\Python37-32\\lib', 'C:\\Program Files (x86)\\Python37-32', 'C:\\Program Files (x86)\\Python37-32\\lib\\site-packages']
Traceback (most recent call last):
  File "monkeytype\cli.py", line 18, in <module>
    from typing import (
  File "d:\work\pyann\monkeytype\monkeytype\typing.py", line 11, in <module>
    from typing import (
ImportError: cannot import name 'Any' from 'typing' (d:\work\pyann\monkeytype\monkeytype\typing.py)
```

The file `monkeytype/typing.py` import itself instead of the Python library `typing`. How do you get around this issue when running monkeytype from the python command-line ?

**Comment by bluebird75** [comment] 2018-09-26 04:33
I also just noticed that the stub is invalid syntax for mypy, the classes should be nested. I did not expect my example to create so much trouble...

**Comment by carljm** [comment] 2018-09-26 19:36
It seems to me this is a duplicate of #114? The syntax error when applying the stub is just because the stub has invalid syntax in it due to the nested classes. I don't see any additional issue beyond that.

Regarding running from command-line, `python -m monkeytype` should work?

**Closed by carljm** 2018-09-26 19:36 UTC

**Comment by bluebird75** [comment] 2018-09-27 12:50
In this issue, the error is reported during apply, there is no stub. That's why I reported it separately.

In this specific case, I believe a more specific error message is needed because the syntax is perfectly valid at forward_ref.py, line 8 and still the user received :

```
d:\work\pyann\monkeytype\toto>monkeytype apply forward_ref
ERROR: Failed applying stub with retype:
error: d:\work\pyann\monkeytype\toto\forward_ref.py: invalid syntax (<unknown>, line 8)
```

Maybe saying that the transformed version is triggerring the error and providing links to the temporary version of the transformed file, for better diagnosis ?

I know I am targetting for high level of user feedback, but clear error messages are invaluable resources for developers (and you can guess that I hate gcc error messages for templates ).
