### ISSUE TITLE
MonkeyType support single file?

### ISSUE THREAD

**Issue by leafonsword** [Instagram/MonkeyType#134] opened 2019-03-20 07:30 UTC
I have a script test.py:
```
def add(a,b):
    return a+b

add(1,2)
```

could MonkeyType support this single file, and generate this appearance:
```
monkeytype run test.py

monkeytype stub test
def add(a: int, b: int) -> int: ...
```

**Comment by carljm** [comment] 2019-03-31 18:37
Hi! This is a duplicate of issue #19. That issue explains some of the pitfalls with doing this that make me a bit skeptical of it, but I'm not totally opposed to the idea if someone puts together a PR that looks solid.

**Closed by carljm** 2019-03-31 18:37 UTC
