### ISSUE TITLE
Crashes with "AttributeError: 'TypeVar' object has no attribute '__qualname__'"

### ISSUE THREAD

**Issue by pradyunsg** [Instagram/MonkeyType#92] opened 2018-06-28 21:23 UTC
**Description**

I'm trying to use MonkeyType to generate annotations for pip by running it over pip's codebase using pip's test suite. The idea is to generate stubs using MonkeyType and then I then manually review and add annotations to the codebase in Py2 style (backwards compat + the test suite coverage isn't 100%).

ISTM that MonkeyType is capable of merging type information from multiple runs. (feel free to correct me if I'm wrong)

**Output**

I ended up with a repeating traceback as follows while trying to use MonkeyType on pip.

<details><br>

```
Failed to serialize trace
Traceback (most recent call last):
  File "/private/var/folders/4d/bt0_xfx56bjfmmt2bv3r5_qh0000gn/T/pytest-of-pradyunsg/pytest-87/test_basic_install_from_wheel0/workspace/venv/lib/python3.6/site-packages/monkeytype/encoding.py", line 216, in serialize_traces
    yield CallTraceRow.from_trace(trace)
  File "/private/var/folders/4d/bt0_xfx56bjfmmt2bv3r5_qh0000gn/T/pytest-of-pradyunsg/pytest-87/test_basic_install_from_wheel0/workspace/venv/lib/python3.6/site-packages/monkeytype/encoding.py", line 177, in from_trace
    arg_types = arg_types_to_json(trace.arg_types)
  File "/private/var/folders/4d/bt0_xfx56bjfmmt2bv3r5_qh0000gn/T/pytest-of-pradyunsg/pytest-87/test_basic_install_from_wheel0/workspace/venv/lib/python3.6/site-packages/monkeytype/encoding.py", line 125, in arg_types_to_json
    type_dict = {name: type_to_dict(typ) for name, typ in arg_types.items()}
  File "/private/var/folders/4d/bt0_xfx56bjfmmt2bv3r5_qh0000gn/T/pytest-of-pradyunsg/pytest-87/test_basic_install_from_wheel0/workspace/venv/lib/python3.6/site-packages/monkeytype/encoding.py", line 125, in <dictcomp>
    type_dict = {name: type_to_dict(typ) for name, typ in arg_types.items()}
  File "/private/var/folders/4d/bt0_xfx56bjfmmt2bv3r5_qh0000gn/T/pytest-of-pradyunsg/pytest-87/test_basic_install_from_wheel0/workspace/venv/lib/python3.6/site-packages/monkeytype/encoding.py", line 74, in type_to_dict
    d['elem_types'] = [type_to_dict(t) for t in elem_types]
  File "/private/var/folders/4d/bt0_xfx56bjfmmt2bv3r5_qh0000gn/T/pytest-of-pradyunsg/pytest-87/test_basic_install_from_wheel0/workspace/venv/lib/python3.6/site-packages/monkeytype/encoding.py", line 74, in <listcomp>
    d['elem_types'] = [type_to_dict(t) for t in elem_types]
  File "/private/var/folders/4d/bt0_xfx56bjfmmt2bv3r5_qh0000gn/T/pytest-of-pradyunsg/pytest-87/test_basic_install_from_wheel0/workspace/venv/lib/python3.6/site-packages/monkeytype/encoding.py", line 74, in type_to_dict
    d['elem_types'] = [type_to_dict(t) for t in elem_types]
  File "/private/var/folders/4d/bt0_xfx56bjfmmt2bv3r5_qh0000gn/T/pytest-of-pradyunsg/pytest-87/test_basic_install_from_wheel0/workspace/venv/lib/python3.6/site-packages/monkeytype/encoding.py", line 74, in <listcomp>
    d['elem_types'] = [type_to_dict(t) for t in elem_types]
  File "/private/var/folders/4d/bt0_xfx56bjfmmt2bv3r5_qh0000gn/T/pytest-of-pradyunsg/pytest-87/test_basic_install_from_wheel0/workspace/venv/lib/python3.6/site-packages/monkeytype/encoding.py", line 67, in type_to_dict
    qualname = typ.__qualname__
AttributeError: 'TypeVar' object has no attribute '__qualname__'
```

</details><br>

**Reproduction**

(I haven't found the time yet to create a distilled reproduction case or look into what might be causing this exactly; so, currently getting to the actual failing test involves quite a few downloads)

In a clean Python 3.6 virtualenv, run the following script:

```sh
# Get the code
git clone https://github.com/pradyunsg/pip.git
cd pip
git checkout a1f1792870cce2f78218088f3ea31aead300d585
# Alternatively, download and unpack
# https://github.com/pradyunsg/pip/archive/a1f1792870cce2f78218088f3ea31aead300d585.zip

# Prepare the testing environment
pip install -r tools/tests-requirements.txt
pip install .

# Run the tests such that it invokes monkeytype 
# Here we run only one test, to ensure this isn't happening because of some sort of
# race condition or interaction of multiple instances.
pytest "tests/functional/test_install_wheel.py::test_basic_install_from_wheel"
```

**Additional Context**
Note that pip's test suite does a lot of things that might make this a little difficult to debug -- almost every creates a new temporary venv from a template venv (this ensures isolation between tests) and installs pip in the new temporary venv which is then invoked via a subprocess that in turn, runs pip with monkeytype collection enabled.

**Comment by carljm** [comment] 2018-06-28 21:52
> ISTM that MonkeyType is capable of merging type information from multiple runs

Yes it is.

Regarding the issue, it looks like some runtime function call that MonkeyType is tracing is receiving in its arguments a generic type whose elements contain a TypeVar. That's a bit strange, normally a TypeVar would never appear in runtime arguments. It's especially odd since pip's codebase doesn't contain any TypeVars. It seems like MonkeyType might be tracing some code it shouldn't be (e.g. stdlib `typing` module maybe).

I will take a deeper look at this but it might be a couple weeks. If you want to dig in the meantime, it would be really interesting to have the full details of the `trace` object in the top two stack frames of the traceback, e.g. by doing a pdb postmortem on the exception.

**Comment by pradyunsg** [comment] 2018-06-29 05:55
Can't drop into pdb directly through pip/monkeytype's code since it's invoked as a subprocess. :(

I ended up just printing the information needed, via traceback inspection in `serialize_traces`; here's the last few frames that might provide useful info.

```
Frame from_trace in <venv>/lib/python3.6/site-packages/monkeytype/encoding.py at line 178
	            qualname = GenericMeta.__subclasscheck__
	              module = typing
	               trace = CallTrace(
	                           <function GenericMeta.__subclasscheck__ at 0x1107bf158>,
	                           {
	                               'self': typing.Type[typing.MutableMapping[~KT, ~VT]],
	                               'cls': typing.Type[pip._internal.req.req_install.InstallRequirement]
	                           },
	                           <class 'bool'>,
	                           None
	                       )
	                 cls = <class 'monkeytype.encoding.CallTraceRow'>

Frame arg_types_to_json in <venv>/lib/python3.6/site-packages/monkeytype/encoding.py at line 126
	           arg_types = {
	                           'self': typing.Type[typing.MutableMapping[~KT, ~VT]],
	                           'cls': typing.Type[pip._internal.req.req_install.InstallRequirement]
	                       }

Frame <dictcomp> in <venv>/lib/python3.6/site-packages/monkeytype/encoding.py at line 126
	                 typ = typing.Type[typing.MutableMapping[~KT, ~VT]]
	                name = self
	                  .0 = <dict_itemiterator object at 0x110bd0228>

Frame type_to_dict in <venv>/lib/python3.6/site-packages/monkeytype/encoding.py at line 75
	          elem_types = (typing.MutableMapping[~KT, ~VT],)
	                   d = {'module': 'typing', 'qualname': 'Type'}
	            qualname = Type
	                 typ = typing.Type[typing.MutableMapping[~KT, ~VT]]

Frame <listcomp> in <venv>/lib/python3.6/site-packages/monkeytype/encoding.py at line 75
	                   t = typing.MutableMapping[~KT, ~VT]
	                  .0 = <tuple_iterator object at 0x110a1eba8>

Frame type_to_dict in <venv>/lib/python3.6/site-packages/monkeytype/encoding.py at line 75
	          elem_types = (~KT, ~VT)
	                   d = {'module': 'typing', 'qualname': 'MutableMapping'}
	            qualname = MutableMapping
	                 typ = typing.MutableMapping[~KT, ~VT]

Frame <listcomp> in <venv>/lib/python3.6/site-packages/monkeytype/encoding.py at line 75
	                   t = ~KT
	                  .0 = <tuple_iterator object at 0x11098c358>

Frame type_to_dict in <venv>/lib/python3.6/site-packages/monkeytype/encoding.py at line 68
	                 typ = ~KT
```

**Comment by carljm** [comment] 2018-06-29 16:58
Nice! So that confirms that the problem is that MonkeyType is tracing function calls in the stdlib `typing` module, which it should not do. There should be a follow-up here for MonkeyType to be more robust when it runs into a TypeVar (or anything else without a `__qualname__`) as an argument. The more immediate question, though, is why is MonkeyType even trying to trace these calls. The default code filter (https://github.com/Instagram/MonkeyType/blob/master/monkeytype/config.py#L111) should prevent this, and it doesn't appear to me that you are installing any custom config that would override that.

My hunch is that the virtualenv-within-a-virtualenv scenario is confusing the default code filter and it is mistakenly failing to identify the location of the standard library. So fixing that would be the other follow-up here.

Probably the easiest workaround for you right now might be to set `MONKEYTYPE_TRACE_MODULES="pip"` environment variable, which should resolve the issue. It explicitly tells MonkeyType to only trace calls within the `pip` namespace and nowhere else.

**Comment by pradyunsg** [comment] 2018-06-30 07:50
> `MONKEYTYPE_TRACE_MODULES="pip"`

This didn't work but I wrote a super non-portable code filter which does the job for me:

```py
if not code.co_filename or code.co_filename[0] == '<':
   return False

filename = pathlib.Path(code.co_filename).resolve()
return "pip" in filename.parts and "_vendor" not in filename.parts
```

Currently trying to figure out how to make monkeytype put the db in a consistent location...

> My hunch is that the virtualenv-within-a-virtualenv scenario is confusing the default code filter and it is mistakenly failing to identify the location of the standard library.

Yeah, that what it looks like. It's not really a common scenario. 📦

**Comment by pradyunsg** [comment] 2018-06-30 07:53
Awesome. I found and used `MT_DB_LOC` to place the database in a consistent location across runs. Don't see it documented though and also, probably the name should start with `MONKEYTYPE_` (for discoverablity).

None the less, here's a feature request:

A command that dumps all the loaded stubs for a name (and sub-names) in a directory (possibly user-specified). I ended up doing this:

```sh
for ln in $(monkeytype list-modules | grep pip._internal)
do
 loc=stubs/$(echo $ln | tr '.' '/')
 mkdir -p $(dirname ${loc})
 echo "=============== ${loc}"
 monkeytype stub $ln > ${loc}.pyi
done
```

**Comment by carljm** [comment] 2018-07-02 17:07
@pradyunsg Glad you got it working! I think your feature request is #26. I filed #95, #96, and #97 for the other follow-ups here. Closing this issue as I think it will be easier to work with each specific follow-up in its own issue. Thanks for the thorough report!

**Closed by carljm** 2018-07-02 17:07 UTC
Labels: bug

**Comment by pradyunsg** [comment] 2018-07-02 17:44
Sounds good to me. Thanks for the help @carljm! ^.^
